### ISSUE TITLE
Broken imports of go.opentelemetry.io/otel/sdk for 1.21.0

### ISSUE THREAD

**Issue by JeromeJu** [tektoncd/pipeline#7464]
When we are trying to bump [go.opentelemetry.io/otel/sdk](https://github.com/tektoncd/pipeline/pull/7387) from 1.19.0 to 1.21.0, [the build test failure](https://prow.tekton.dev/view/gs/tekton-prow/pr-logs/pull/tektoncd_pipeline/7387/pull-tekton-pipeline-build-tests/1732420754873520128#1:build-log.txt%3A1664)  indicates the tracerProvider [@HEAD](https://github.com/tektoncd/pipeline/commit/6a5f0eb50e59aa1d4a800726abe94bb41557d8f9) has not implemented the interface from the upstream.

```
pkg/reconciler/taskrun/controller.go:92:30: cannot use tracerProvider (variable of type *tracing.tracerProvider) as type "go.opentelemetry.io/otel/trace".TracerProvider in struct literal:
	*tracing.tracerProvider does not implement "go.opentelemetry.io/otel/trace".TracerProvider (missing tracerProvider method)
```

When looking into this, there seems to be 2 issues that need verification:
- The tracerProvider interface has changed in this version upgrade with an embeddedTracerProvider: https://github.com/open-telemetry/opentelemetry-go/blob/d37d851bbce65577ab340849ec6c540fdc6e3096/trace/embedded/embedded.go#L36
- [trace.NewNoopTracerProvider()](https://github.com/tektoncd/pipeline/blob/6a5f0eb50e59aa1d4a800726abe94bb41557d8f9/pkg/tracing/tracing.go#L53) is deprecated and the up-to-date func should have the interface implemented.

_Originally posted by @JeromeJu in https://github.com/tektoncd/pipeline/issues/7387#issuecomment-1843395375_

**Comment by JeromeJu** [comment]
cc @kmjayadeep

**Comment by kmjayadeep** [comment]
I'm working on updating to otel 1.21. It also deprecated jaeger exporter in favor of otel exporter, which makes the update not so-straightforward. 
You can find the WIP PR [here](https://github.com/kmjayadeep/pipeline/pull/6)

Is this blocking anyone currently?

**Comment by JeromeJu** [comment]
> I'm working on updating to otel 1.21. It also deprecated jaeger exporter in favor of otel exporter, which makes the update not so-straightforward. You can find the WIP PR [here](https://github.com/kmjayadeep/pipeline/pull/6)

Thanks for this! I think this PR also works fine for the bump, just failed the go coverage test IIUC.

> Is this blocking anyone currently?
I don't think this is a blocker at the moment.

**Comment by vdemeester** [comment]
@kmjayadeep the bump to containerd "seems" blocked on this.

**Comment by vdemeester** [comment]
A lot of dependabot PRs are blocked on this. For some reason, dependabot tries to update it with other dependencies, making them all fail (instead of just updating the ones).

**Comment by kmjayadeep** [comment]
@vdemeester I will check my WIP PR once again and raise upstream in the next couple of days

**Comment by JeromeJu** [comment]
I can reopen this https://github.com/tektoncd/pipeline/pull/7465 if it looks good. @vdemeester @kmjayadeep

**Comment by kmjayadeep** [comment]
The proper solution is to migrate jaeger to otel exporter and upgrade to 1.21. I have raised https://github.com/tektoncd/pipeline/pull/7547 for this.

@JeromeJu In your PR, jaeger exporter is from otel 1.17 and SDK is 1.21. I'm not sure if there will be any compatibility issues with that. But if it works without issues, I would suggest to go ahead with it and unblock others. I can rebase afterwards on my PR. 7547 will take longer to review and test anyway.
